services:
    - docker

language: go

go:
    - tip

env:
  global:
    - GO111MODULE=on
    - COMMIT: ${TRAVIS_COMMIT::8}
    - IMAGE: drandorg/drand

# https://arslan.io/2018/08/26/using-go-modules-with-vendor-support-on-travis-ci/
install: true

script:
    - make test-unit
    - docker build -t $IMAGE . #docker-compose should be self-sufficient, but fails on travis...
    # keep environnement variable for sudo
    - sudo -E env "PATH=$PATH" make test-integration

before_deploy:
    - docker tag $IMAGE $IMAGE:$COMMIT;
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
    provider: script
    script: docker push $IMAGE
    on:
        branch: master
        repo: drand/drand
