#dist: trusty
sudo: required

services:
    - docker

language: go

go:
    - tip

env:
    - GO111MODULE=on

# https://arslan.io/2018/08/26/using-go-modules-with-vendor-support-on-travis-ci/
install: true

before_script: 
    - docker build -t drand-it . #docker-compose should be self-sufficient, but fails on travis...

script:
    - make test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
        sudo docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        sudo docker push dedis/drand:latest;
    fi

before_deploy:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
