name: TOC

on:
  pull_request:
    branches: [ master ]

jobs:
  toc:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - name: TOC Generator
        uses: technote-space/toc-generator@v2.4.0
        with:
          OPENING_COMMENT: "<!-- START "
          CLOSING_COMMENT: "<!-- END "
          TOC_TITLE: "## Table of Contents"
          CREATE_PR: false
          TARGET_PATHS: "README.md,cmd/relay-gossip/README.md"
